AWSTemplateFormatVersion: '2010-09-09-OC'
Description: CRC project | Infrastructure as Code (IaC) for AWS Organizations

Organization:
  ManagementAccount:
    Type: OC::ORG::MasterAccount
    Properties:
      AccountName: CRC Management
      AccountId: '657006586504'
      RootEmail: crc.pancheliuga@gmail.com

  OrganizationRoot:
    Type: OC::ORG::OrganizationRoot
    Properties:
      DefaultOrganizationAccessRoleName: OrganizationAccountAccessRole
      ServiceControlPolicies:
        - !Ref DenyChangeOfOrgRoleSCP
        - !Ref RestrictUnusedRegionsSCP

  SecurityOU:
    Type: OC::ORG::OrganizationalUnit
    Properties:
      OrganizationalUnitName: Security
      OrganizationalUnits:
        - !Ref SecProdOU

  SecProdOU:
    Type: OC::ORG::OrganizationalUnit
    Properties:
      OrganizationalUnitName: Prod
      Accounts:
        - !Ref LogArchiveProdAccount
        - !Ref SecurityToolingProdAccount

  WorkloadsOU:
    Type: OC::ORG::OrganizationalUnit
    Properties:
      OrganizationalUnitName: Workloads
      OrganizationalUnits:
        - !Ref WorkProdOU
        - !Ref WorkTestOU

  WorkProdOU:
    Type: OC::ORG::OrganizationalUnit
    Properties:
      OrganizationalUnitName: Prod
      Accounts:
        - !Ref WorkloadAProdAccount

  WorkTestOU:
    Type: OC::ORG::OrganizationalUnit
    Properties:
      OrganizationalUnitName: Test
      Accounts:
        - !Ref WorkloadATestAccount

  LogArchiveProdAccount:
    Type: OC::ORG::Account
    Properties:
      Alias: crc-log-archive-prod
      AccountName: log-archive-prod
      RootEmail: crc.pancheliuga+log-archive-prod@gmail.com
      Tags:
        budget-alarm-threshold: '5'
        account-owner-email: pancheliuga.o@gmail.com

  SecurityToolingProdAccount:
    Type: OC::ORG::Account
    Properties:
      Alias: crc-security-tooling-prod
      AccountName: security-tooling-prod
      RootEmail: crc.pancheliuga+security-tooling-prod@gmail.com
      Tags:
        budget-alarm-threshold: '5'
        account-owner-email: pancheliuga.o@gmail.com

  WorkloadAProdAccount:
    Type: OC::ORG::Account
    Properties:
      Alias: crc-work-load-a-prod
      AccountName: work-load-a-prod
      RootEmail: crc.pancheliuga+work-load-a-prod@gmail.com
      Tags:
        budget-alarm-threshold: '5'
        account-owner-email: pancheliuga.o@gmail.com

  WorkloadATestAccount:
    Type: OC::ORG::Account
    Properties:
      Alias: crc-work-load-a-test
      AccountName: work-load-a-test
      RootEmail: crc.pancheliuga+work-load-a-test@gmail.com
      Tags:
        budget-alarm-threshold: '5'
        account-owner-email: pancheliuga.o@gmail.com

  DenyChangeOfOrgRoleSCP:
    Type: OC::ORG::ServiceControlPolicy
    Properties:
      PolicyName: DenyChangeOfOrgRole
      Description: Deny changing the IAM role used for organization access
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DenyChangeOfOrgRole
            Effect: Deny
            Action:
              - 'iam:Attach*'
              - 'iam:Create*'
              - 'iam:Delete*'
              - 'iam:Detach*'
              - 'iam:PutRole*'
              - 'iam:Update*'
            Resource:
              - 'arn:aws:iam::*:role/OrganizationAccountAccessRole'

  RestrictUnusedRegionsSCP:
    Type: OC::ORG::ServiceControlPolicy
    Properties:
      PolicyName: RestrictUnusedRegions
      Description: Restrict Unused regions
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DenyUnsupportedRegions
            Effect: Deny
            NotAction:
              - 'cloudfront:*'
              - 'iam:*'
              - 'route53:*'
              - 'support:*'
              - 'budgets:*'
            Resource: '*'
            Condition:
              StringNotEquals:
                'aws:RequestedRegion':
                  - eu-central-1
